import {
    FallRiskAlert,
    FallRiskAnalysis,
    FallRiskRecommendation,
    MobilityCoachingPlan,
} from '../../types/fallRisk';
import { localFallRiskEngine } from '../fallDetection/FallRiskEngine';
import { api } from './client';

export const fallRiskService = {
    /**
     * Fetches real-time fall risk analysis with K-Means cluster data.
     * Falls back to local sensor-driven engine if backend unavailable.
     */
    getAnalysis: async (userId: string): Promise<FallRiskAnalysis> => {
        try {
            return await api.get<FallRiskAnalysis>(`/v1/fall-risk/analysis/${userId}`);
        } catch (error) {
            console.warn('API unavailable, using local sensor-driven Fall Risk Engine', error);
            return await localFallRiskEngine.getAnalysis();
        }
    },

    /**
     * Fetches AI-generated personalized mobility coaching plan.
     * This is a separate call from getAnalysis() to keep the main dashboard fast
     * (Groq LLM inference takes ~1 second; we load it lazily after the UI renders).
     */
    getCoachingPlan: async (userId: string): Promise<MobilityCoachingPlan> => {
        return await api.get<MobilityCoachingPlan>(`/v1/fall-risk/coaching/${userId}`);
    },

    /**
     * Fetches active fall risk alerts generated by the sensor processing pipeline.
     */
    getAlerts: async (userId: string): Promise<FallRiskAlert[]> => {
        try {
            return await api.get<FallRiskAlert[]>(`/v1/fall-risk/alerts/${userId}`);
        } catch (error) {
            console.error('Failed to fetch fall risk alerts', error);
            return [];
        }
    },

    /**
     * Fetches AI-powered fall prevention recommendations (sourced from coaching plan).
     */
    getRecommendations: async (userId: string): Promise<FallRiskRecommendation[]> => {
        try {
            return await api.get<FallRiskRecommendation[]>(`/v1/fall-risk/recommendations/${userId}`);
        } catch (error) {
            console.error('Failed to fetch fall risk recommendations', error);
            return [];
        }
    },

    /**
     * Updates the caregiver notification threshold on the server.
     */
    updateThreshold: async (userId: string, threshold: number): Promise<void> => {
        try {
            await api.patch(`/v1/fall-risk/settings/${userId}`, { alertThreshold: threshold });
        } catch (error) {
            console.error('Failed to update threshold on server', error);
            throw error;
        }
    },
};
