import {
    FallRiskAlert,
    FallRiskAnalysis,
    FallRiskRecommendation,
} from '../../types/fallRisk';
import { localFallRiskEngine } from '../fallDetection/FallRiskEngine';
import { api } from './client';

export const fallRiskService = {
    /**
     * Fetches real-time fall risk analysis.
     * Tries the backend API first, falls back to local sensor-driven engine if unavailable.
     */
    getAnalysis: async (userId: string): Promise<FallRiskAnalysis> => {
        try {
            return await api.get<FallRiskAnalysis>(`/v1/fall-risk/analysis/${userId}`);
        } catch (error) {
            console.warn("API unavailable, using local sensor-driven Fall Risk Engine", error);
            // This ensures logic works with real values from the device when server is down
            return await localFallRiskEngine.getAnalysis();
        }
    },


    /**
     * Fetches active fall risk alerts generated by the sensor processing pipeline
     */
    getAlerts: async (userId: string): Promise<FallRiskAlert[]> => {
        try {
            return await api.get<FallRiskAlert[]>(`/v1/fall-risk/alerts/${userId}`);
        } catch (error) {
            console.error("Failed to fetch fall risk alerts", error);
            // Return empty array instead of throwing to keep dashboard functional
            return [];
        }
    },

    /**
     * Fetches personalized fall prevention recommendations
     */
    getRecommendations: async (userId: string): Promise<FallRiskRecommendation[]> => {
        try {
            return await api.get<FallRiskRecommendation[]>(`/v1/fall-risk/recommendations/${userId}`);
        } catch (error) {
            console.error("Failed to fetch fall risk recommendations", error);
            return [];
        }
    },

    /**
     * Updates the caregiver notification threshold on the server
     */
    updateThreshold: async (userId: string, threshold: number): Promise<void> => {
        try {
            await api.patch(`/v1/fall-risk/settings/${userId}`, { alertThreshold: threshold });
            console.log(`Successfully updated threshold for ${userId} to ${threshold}`);
        } catch (error) {
            console.error("Failed to update threshold on server", error);
            throw error;
        }
    }
};

